"""Sync breakout signals to the sibling ValueInvesting repository."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from qlib_research.config import (  # noqa: E402
    get_project_root,
    get_valueinvesting_root,
)
from qlib_research.io.artifacts import (  # noqa: E402
    BREAKOUT_MANIFEST_FILE,
    BREAKOUT_SIGNALS_FILE,
    get_breakout_signals_dir,
    get_latest_breakout_model,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync breakout signals to ValueInvesting",
    )
    parser.add_argument("--source", default=None,
                        help="Source signals dir (default: artifacts/breakout/signals/)")
    parser.add_argument("--target", default=None,
                        help="Target dir in ValueInvesting "
                             "(default: <VI>/data/qlib_artifacts/breakout/)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be synced without doing it")
    return parser.parse_args()


def _default_source() -> Path:
    return get_breakout_signals_dir()


def _default_target() -> Path:
    try:
        vi_root = get_valueinvesting_root()
    except Exception:
        vi_root = get_project_root().parent / "ValueInvesting"
    return (vi_root / "data" / "qlib_artifacts" / "breakout").resolve()


def _load_model_meta(model_path: Path | None) -> dict[str, Any]:
    if model_path is None:
        return {}
    meta_path = model_path.with_suffix(".json")
    if not meta_path.exists():
        return {}
    try:
        return json.loads(meta_path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _ensure_manifest(source_dir: Path, signals_path: Path) -> Path:
    """Make sure ``manifest_breakout.json`` exists alongside the signals.

    When the upstream score script has not produced one (e.g. signals were
    generated by an external tool), synthesise a minimal manifest from the
    latest model metadata so downstream consumers always see one.
    """
    manifest_path = source_dir / BREAKOUT_MANIFEST_FILE
    if manifest_path.exists():
        return manifest_path

    latest_model = get_latest_breakout_model()
    model_meta = _load_model_meta(latest_model)

    manifest = {
        "model_id": latest_model.stem if latest_model else None,
        "model_path": str(latest_model) if latest_model else None,
        "signals_path": signals_path.name,
        "frequency": "daily",
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "signal_count": _count_signals(signals_path),
        "model_metrics": (model_meta.get("metrics")
                          if isinstance(model_meta, dict) else None),
        "synthesised": True,
    }
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )
    return manifest_path


def _count_signals(signals_path: Path) -> int:
    if not signals_path.exists():
        return 0
    try:
        with signals_path.open("r", encoding="utf-8") as f:
            # First line is the header.
            return max(0, sum(1 for _ in f) - 1)
    except Exception:
        return 0


def _plan(source: Path, target: Path) -> dict[str, Any]:
    signals_src = source / BREAKOUT_SIGNALS_FILE
    manifest_src = source / BREAKOUT_MANIFEST_FILE
    return {
        "source_dir": str(source),
        "target_dir": str(target),
        "signals_file": {
            "source": str(signals_src),
            "target": str(target / BREAKOUT_SIGNALS_FILE),
            "exists": signals_src.exists(),
        },
        "manifest_file": {
            "source": str(manifest_src),
            "target": str(target / BREAKOUT_MANIFEST_FILE),
            "exists": manifest_src.exists(),
        },
    }


def main() -> None:
    args = parse_args()
    source_dir = (Path(args.source).expanduser().resolve()
                  if args.source else _default_source())
    target_dir = (Path(args.target).expanduser().resolve()
                  if args.target else _default_target())

    print("=" * 70)
    print("Breakout signals sync → ValueInvesting")
    print("=" * 70)
    print(f"Source: {source_dir}")
    print(f"Target: {target_dir}")

    if not source_dir.exists():
        print(f"ERROR: source directory not found: {source_dir}", file=sys.stderr)
        print("Run `python scripts/score_breakout_candidates.py` first.",
              file=sys.stderr)
        sys.exit(2)

    signals_path = source_dir / BREAKOUT_SIGNALS_FILE
    if not signals_path.exists():
        print(f"ERROR: missing {BREAKOUT_SIGNALS_FILE} in {source_dir}",
              file=sys.stderr)
        sys.exit(2)

    # Ensure a manifest exists, generating one if necessary (also in dry-run we
    # report what we *would* synthesise but don't write it).
    manifest_path = source_dir / BREAKOUT_MANIFEST_FILE
    if not manifest_path.exists() and not args.dry_run:
        manifest_path = _ensure_manifest(source_dir, signals_path)
        print(f"[info] synthesised manifest: {manifest_path}")

    plan = _plan(source_dir, target_dir)
    plan["signal_count"] = _count_signals(signals_path)
    plan["dry_run"] = bool(args.dry_run)

    print("\nPlan:")
    print(json.dumps(plan, ensure_ascii=False, indent=2, default=str))

    if args.dry_run:
        print("\n[dry-run] No files copied.")
        return

    target_dir.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    shutil.copy2(signals_path, target_dir / BREAKOUT_SIGNALS_FILE)
    copied.append(BREAKOUT_SIGNALS_FILE)
    if manifest_path.exists():
        shutil.copy2(manifest_path, target_dir / BREAKOUT_MANIFEST_FILE)
        copied.append(BREAKOUT_MANIFEST_FILE)

    print(f"\nSynced {len(copied)} files to {target_dir}: {copied}")


if __name__ == "__main__":
    main()
